# Generated by Django 4.0.4 on 2022-05-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('effective_date', models.DateField()),
                ('prev_policy_cancelled', models.BooleanField(default=False)),
                ('owns_insure_property', models.BooleanField(default=False)),
                ('property_zip', models.CharField(max_length=10)),
                ('property_state', models.CharField(max_length=2)),
            ],
        ),
    ]
